#!/usr/bin/env perl

main() if $0 eq __FILE__;

use strict;
use File::Basename;
use lib dirname($0);
use md2bl;

sub main {
    if ($#ARGV+1 < 1) {
        die "引数にマークダウンファイルを指定してください";
    }
    my $file = @ARGV[0];
    my $backlog = "";
    open(IN, $file) or die "$!";
    while (<IN>) {
        $backlog .= md2bl::md2bl($_);
    }
    close (IN);

    print $backlog;
}
