version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      - run: apt-get update -y && apt-get install openssh-client git

    steps:
      - checkout

      - run:
          name: Test
          command: perl test.pl

